services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter

  backend:
    build: ${BACKEND_IMAGE}
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start"]
    environment:
      DB_HOST: db

  frontend:
    build: ${FRONTEND_IMAGE}
    ports:
      - "3000:80"
    depends_on:
      - backend
